/**
  ******************************************************************************
  * Author  VMA Application Team (mv737)
  * Version V1.0.7
  * Date    4-April-2016
  * Brief   Node-locked license for osx_motion_fx module
  ******************************************************************************
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  ******************************************************************************
  */

/* Below line has to be removed once the license has been edited with valid codes */
#ifndef _OSX_MOTION_FX_LICENSE_
#define _OSX_MOTION_FX_LICENSE_
uint32_t osx_mfx_license[3][4] =
{
{ 0x4179FF8B, 0x9F7582CF, 0x09EAE338, 0x857D6684 },
{ 0x630E2677, 0x166FDE0F, 0x4ED8FD4F, 0x3A5AB519 },
{ 0x236DB5C3, 0x760B4854, 0x7F60744B, 0x23CA44D5 }
};
#endif /* _OSX_MOTION_FX_LICENSE_ */
